FROM ubuntu:16.04
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-lang-cyrillic asymptote ghostscript
WORKDIR /home
